<?php

return array (
  'name' => '我的网站',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'user' => '会员配置',
    'auth_area' => '权限划分',
    'people' => '人员等级',
    'river_type' => '河湖类型',
    'river_attribute' => '河湖属性',
    'river_level' => '水域等级',
    'mon_type' => '监测类型',
    'section_type' => '断面类型',
    'control_level' => '控制级别',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'jbq' => '江北区',
  'ccz' => '慈城镇',
  'kpjd' => '孔浦街道',
  'qjjd' => '前江街道',
  'wjjd' => '文教街道',
  'yjjd' => '甬江街道',
  'wtjd' => '外滩街道',
  'zqjd' => '庄桥街道',
  'htjd' => '洪塘街道',
  'first' => '一等',
  'second' => '二等',
  'river_course' => '河道',
  'subsection' => '分段',
  'tributary' => '支流',
  'nothing' => '无',
  'top_flow' => '顶流',
  'towns' => '乡镇级',
  'city' => '市级',
  'county' => '县（区）级',
  'lake' => '湖泊',
  'reservoir' => '水库',
  'comprehensive' => '综合水质评价',
  'phosphorus' => '总磷',
  'ammonia_nitrogen' => '氨氮',
  'dissolved_oxygen' => '溶解氧',
  'permanganate' => '高锰酸盐指数',
  'jcdw' => '检测点位',
  'people_controller' => '人工控制',
  'county_controller' => '县控',
);
